### PR TITLE
Close #29 fix wrong scoping review when create feedback

### LINKED ISSUE #29: fix wrong scoping review when create feedback

### PR DESCRIPTION
**Pull request by lyden29**

### CODE REVIEW

File: app/serializers/spree/v2/storefront/review_detail_with_feedback_serializer.rb [hunk 1]
```diff
@@ -12,7 +12,7 @@ class ReviewDetailWithFeedbackSerializer < BaseSerializer
         end
 
         attribute :is_own_review do |review, params|
-          params[:user].present? && params[:user].id == user.id
+          params[:user].present? && params[:user].id == review.user.id
```
Comment (channainfo) [inline app/serializers/spree/v2/storefront/review_detail_with_feedback_serializer.rb:15]: @lyden29  use review.user_id instead to avoid triggering extra queries.

**Review by channainfo — CHANGES_REQUESTED** [review]
